# Generated by Django 5.2 on 2026-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría (ej: Medicamentos, Insumos, Equipos)', max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría (opcional)', verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='categorias_nombre_bb19a2_idx'), models.Index(fields=['created_at'], name='categorias_created_f95942_idx')],
            },
        ),
    ]
