# Generated by Django 5.2 on 2026-04-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(help_text='Código único de identificación interna del producto', max_length=50, unique=True, verbose_name='código interno')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras del producto (opcional)', max_length=100, verbose_name='código de barras')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='nombre')),
                ('marca', models.CharField(blank=True, help_text='Marca o fabricante del producto', max_length=100, verbose_name='marca')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='descripción')),
                ('existencias', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible en inventario', max_digits=10, verbose_name='existencias')),
                ('invima', models.CharField(blank=True, help_text='Registro sanitario INVIMA (si aplica)', max_length=100, verbose_name='invima')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio al que se compró el producto', max_digits=12, verbose_name='precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al que se vende el producto', max_digits=12, verbose_name='precio de venta')),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA aplicable (0-100)', max_digits=5, verbose_name='IVA')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/', verbose_name='imagen')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el producto ingresó al inventario', verbose_name='fecha de ingreso')),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Fecha de caducidad del producto (si aplica)', null=True, verbose_name='fecha de caducidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_interno'], name='productos_codigo__80de2d_idx'), models.Index(fields=['codigo_barras'], name='productos_codigo__aa601e_idx'), models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'), models.Index(fields=['categoria'], name='productos_categor_169a62_idx'), models.Index(fields=['existencias'], name='productos_existen_91950b_idx'), models.Index(fields=['fecha_caducidad'], name='productos_fecha_c_d2de4e_idx'), models.Index(fields=['created_at'], name='productos_created_99b305_idx')],
            },
        ),
    ]
