# Generated by Django 5.2 on 2026-04-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_interno',
            field=models.IntegerField(blank=True, help_text='Código único numérico autoincremental para identificación interna', null=True, unique=True, verbose_name='código interno'),
        ),
    ]
