# Generated by Django 5.2 on 2026-04-23 04:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_codigo_interno_to_integer'),
        ('proveedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de la factura del proveedor', max_length=50, unique=True, verbose_name='número de factura')),
                ('fecha_factura', models.DateField(help_text='Fecha de emisión de la factura', verbose_name='fecha de factura')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro en el sistema', verbose_name='fecha de registro')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de los valores antes de impuestos y descuentos', max_digits=12, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor del impuesto al valor agregado', max_digits=12, verbose_name='IVA')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a la factura', max_digits=12, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de la factura (subtotal + IVA - descuento)', max_digits=12, verbose_name='total')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la factura', verbose_name='observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada')], default='PENDIENTE', help_text='Estado actual de la factura', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que emitió la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor', verbose_name='proveedor')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario que registró la factura en el sistema', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario de registro')),
            ],
            options={
                'verbose_name': 'factura de compra',
                'verbose_name_plural': 'facturas de compra',
                'db_table': 'facturas_compra',
                'ordering': ['-fecha_factura', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad comprada del producto', max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al que se compró el producto', max_digits=12, verbose_name='precio unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de IVA aplicado al producto (0-100)', max_digits=5, verbose_name='IVA')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a este producto', max_digits=12, verbose_name='descuento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
                ('producto', models.ForeignKey(help_text='Producto comprado', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='producto')),
                ('factura', models.ForeignKey(help_text='Factura de compra a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.facturacompra', verbose_name='factura')),
            ],
            options={
                'verbose_name': 'detalle de factura de compra',
                'verbose_name_plural': 'detalles de factura de compra',
                'db_table': 'detalles_factura_compra',
                'ordering': ['factura', 'producto'],
            },
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['numero_factura'], name='facturas_co_numero__79c962_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['proveedor'], name='facturas_co_proveed_c9612c_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['fecha_factura'], name='facturas_co_fecha_f_304299_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['estado'], name='facturas_co_estado_889461_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['usuario_registro'], name='facturas_co_usuario_36285b_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['created_at'], name='facturas_co_created_40a2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturacompra',
            index=models.Index(fields=['factura'], name='detalles_fa_factura_3bee37_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturacompra',
            index=models.Index(fields=['producto'], name='detalles_fa_product_eb6142_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefacturacompra',
            index=models.Index(fields=['created_at'], name='detalles_fa_created_b4c9ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallefacturacompra',
            unique_together={('factura', 'producto')},
        ),
    ]
