# Generated by Django 5.2 on 2026-04-23 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_facturacompra_detallefacturacompra_and_more'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], help_text='Tipo de movimiento: Entrada, Salida o Ajuste', max_length=20, verbose_name='tipo de movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad movida (positiva para entrada, negativa para salida)', max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto al momento del movimiento', max_digits=12, verbose_name='precio unitario')),
                ('motivo', models.CharField(help_text='Motivo o descripción del movimiento', max_length=200, verbose_name='motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento', verbose_name='fecha')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el movimiento', verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura de compra asociada a la entrada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='inventario.facturacompra', verbose_name='factura de compra')),
                ('producto', models.ForeignKey(help_text='Producto al que se le registra el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='inventario.producto', verbose_name='producto')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('venta', models.ForeignKey(blank=True, help_text='Venta asociada a la salida (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ventas.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'registro de historial de inventario',
                'verbose_name_plural': 'registros de historial de inventario',
                'db_table': 'historial_inventario',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['producto'], name='historial_i_product_7e2376_idx'), models.Index(fields=['tipo_movimiento'], name='historial_i_tipo_mo_12c4ef_idx'), models.Index(fields=['fecha'], name='historial_i_fecha_0be2e7_idx'), models.Index(fields=['usuario'], name='historial_i_usuario_1fd4e0_idx'), models.Index(fields=['factura'], name='historial_i_factura_aec33d_idx'), models.Index(fields=['venta'], name='historial_i_venta_i_1684c0_idx')],
            },
        ),
    ]
