# Generated by Django 6.0.4 on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_detallefacturacompra_precio_venta_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estandar_codigo',
            field=models.CharField(
                default='999',
                help_text='Codigo de estandar del producto requerido por Factus.',
                max_length=10,
                verbose_name='codigo estandar',
            ),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida_codigo',
            field=models.CharField(
                default='94',
                help_text='Codigo de unidad de medida requerido por Factus.',
                max_length=10,
                verbose_name='codigo unidad de medida',
            ),
        ),
    ]
