# Generated by Django 6.0.4 on 2026-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_facturacion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturacompra',
            name='precio_venta_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta que se aplicara al procesar la factura', max_digits=12, null=True, verbose_name='precio de venta sugerido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estandar_codigo',
            field=models.CharField(default='999', help_text='Codigo estandar del producto para facturación electrónica', max_length=10, verbose_name='codigo estandar'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida_codigo',
            field=models.CharField(default='94', help_text='Codigo Factus/DIAN de la unidad de medida del producto', max_length=10, verbose_name='codigo de unidad de medida'),
        ),
    ]
