# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('inventario', '0008_alter_detallefacturacompra_precio_venta_sugerido_and_more'),
        ('proveedor', '0003_proveedor_empresa_alter_proveedor_numero_documento_and_more'),
        ('ventas', '0007_factuscredential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura_compra', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_inventario', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre único de la categoría (ej: Medicamentos, Insumos, Equipos)', max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(help_text='Número único de la factura del proveedor', max_length=50, verbose_name='número de factura'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_interno',
            field=models.IntegerField(blank=True, help_text='Código único numérico autoincremental para identificación interna', null=True, verbose_name='código interno'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['empresa'], name='categorias_empresa_23c84b_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['empresa'], name='facturas_co_empresa_3cade8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinventario',
            index=models.Index(fields=['empresa'], name='historial_i_empresa_2481c5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa'], name='productos_empresa_eb8cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='categoria_empresa_nombre_unique'),
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_factura'), name='factura_compra_empresa_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_interno'), name='producto_empresa_codigo_unique'),
        ),
    ]
