# Generated by Django 6.0.4 on 2026-05-21 17:48

import django.db.models.deletion
import django.utils.timezone
from datetime import datetime, time
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrar_facturas_existentes_a_abonos(apps, schema_editor):
    FacturaCompra = apps.get_model('inventario', 'FacturaCompra')
    AbonoFacturaCompra = apps.get_model('inventario', 'AbonoFacturaCompra')

    for factura in FacturaCompra.objects.filter(total__gt=0):
        if not factura.usuario_registro_id:
            continue
        fecha_pago = datetime.combine(factura.fecha_factura, time.min)
        if django.utils.timezone.is_naive(fecha_pago):
            fecha_pago = django.utils.timezone.make_aware(fecha_pago)
        AbonoFacturaCompra.objects.get_or_create(
            factura_id=factura.id,
            monto=factura.total,
            defaults={
                'empresa_id': factura.empresa_id,
                'metodo_pago': 'EFECTIVO',
                'fecha_pago': fecha_pago,
                'observaciones': 'Pago migrado desde factura de compra existente.',
                'usuario_registro_id': factura.usuario_registro_id,
            },
        )
        FacturaCompra.objects.filter(pk=factura.pk).update(
            total_abonado=factura.total,
            saldo_pendiente=Decimal('0.00'),
            estado_pago='PAGADA',
        )


def revertir_abonos_migrados(apps, schema_editor):
    AbonoFacturaCompra = apps.get_model('inventario', 'AbonoFacturaCompra')
    AbonoFacturaCompra.objects.filter(
        observaciones='Pago migrado desde factura de compra existente.',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresaconfiguracion_ticket_footer_text'),
        ('inventario', '0012_producto_es_producto_especial'),
        ('proveedor', '0003_proveedor_empresa_alter_proveedor_numero_documento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abonos_facturas_compra',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABONADA', 'Abonada'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, verbose_name='estado de pago'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha limite de pago de la factura', null=True, verbose_name='fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito')], default='CONTADO', max_length=20, verbose_name='forma de pago'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='metodo de pago'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo pendiente'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='total_abonado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total abonado'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['fecha_vencimiento'], name='facturas_co_fecha_v_d8f93f_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['estado_pago'], name='facturas_co_estado__c5c62b_idx'),
        ),
        migrations.AddField(
            model_name='abonofacturacompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos_facturas_compra', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='abonofacturacompra',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='inventario.facturacompra', verbose_name='factura de compra'),
        ),
        migrations.AddField(
            model_name='abonofacturacompra',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_facturas_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='abonofacturacompra',
            index=models.Index(fields=['empresa'], name='abonos_fact_empresa_046f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='abonofacturacompra',
            index=models.Index(fields=['factura'], name='abonos_fact_factura_491301_idx'),
        ),
        migrations.AddIndex(
            model_name='abonofacturacompra',
            index=models.Index(fields=['fecha_pago'], name='abonos_fact_fecha_p_94e137_idx'),
        ),
        migrations.AddIndex(
            model_name='abonofacturacompra',
            index=models.Index(fields=['metodo_pago'], name='abonos_fact_metodo__b2d04e_idx'),
        ),
        migrations.RunPython(
            migrar_facturas_existentes_a_abonos,
            revertir_abonos_migrados,
        ),
    ]
