# Generated by Django 5.2 on 2026-04-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(blank=True, help_text='Número único de venta (será generado automáticamente)', max_length=50, null=True, unique=True, verbose_name='número de venta')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta', verbose_name='fecha de venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
                'indexes': [models.Index(fields=['numero_venta'], name='ventas_numero__d43a36_idx'), models.Index(fields=['fecha_venta'], name='ventas_fecha_v_df623b_idx')],
            },
        ),
    ]
