# Generated by Django 6.0.4 on 2026-04-25 00:00

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('usuario', '0002_alter_usuario_email_alter_usuario_id'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(
                blank=True,
                help_text='Cliente asociado a la venta.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ventas',
                to='cliente.cliente',
                verbose_name='cliente',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Descuento global aplicado a la venta.',
                max_digits=12,
                verbose_name='descuento',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(
                choices=[
                    ('PENDIENTE', 'Pendiente'),
                    ('TERMINADA', 'Terminada'),
                    ('CANCELADA', 'Cancelada'),
                ],
                default='PENDIENTE',
                help_text='Estado operativo de la venta.',
                max_length=20,
                verbose_name='estado',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(
                choices=[
                    ('PENDIENTE', 'Pendiente'),
                    ('PARCIAL', 'Parcial'),
                    ('PAGADA', 'Pagada'),
                ],
                default='PENDIENTE',
                help_text='Estado del pago de la venta.',
                max_length=20,
                verbose_name='estado de pago',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='factura_electronica',
            field=models.BooleanField(
                default=False,
                help_text='Indica si la venta requiere factura electronica.',
                verbose_name='factura electronica',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_facturacion',
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    'Fecha y hora de emision de la factura electronica.'
                ),
                null=True,
                verbose_name='fecha de facturacion',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='impuestos',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Valor total de impuestos de la venta.',
                max_digits=12,
                verbose_name='impuestos',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(
                choices=[
                    ('EFECTIVO', 'Efectivo'),
                    ('TARJETA', 'Tarjeta'),
                    ('TRANSFERENCIA', 'Transferencia'),
                    ('CREDITO', 'Credito'),
                ],
                default='EFECTIVO',
                help_text='Metodo de pago principal de la venta.',
                max_length=20,
                verbose_name='metodo de pago',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura_electronica',
            field=models.CharField(
                blank=True,
                help_text='Consecutivo de la factura electronica emitida.',
                max_length=50,
                verbose_name='numero de factura electronica',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(
                blank=True,
                help_text='Observaciones adicionales sobre la venta.',
                verbose_name='observaciones',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Valor pendiente por pagar.',
                max_digits=12,
                verbose_name='saldo pendiente',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Subtotal de la venta antes de impuestos.',
                max_digits=12,
                verbose_name='subtotal',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Valor total final de la venta.',
                max_digits=12,
                verbose_name='total',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_abonado',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Valor abonado hasta el momento.',
                max_digits=12,
                verbose_name='total abonado',
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_registro',
            field=models.ForeignKey(
                default=1,
                help_text='Usuario que registro la venta.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ventas_registradas',
                to='usuario.usuario',
                verbose_name='usuario de registro',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Fecha y hora de creacion del registro.',
                verbose_name='fecha de creacion',
            ),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Fecha y hora de registro de la venta.',
                verbose_name='fecha de venta',
            ),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(
                blank=True,
                help_text='Numero unico de venta generado automaticamente.',
                max_length=30,
                unique=True,
                verbose_name='numero de venta',
            ),
        ),
        migrations.AlterField(
            model_name='venta',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Fecha y hora de la ultima actualizacion.',
                verbose_name='fecha de actualizacion',
            ),
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={
                'ordering': ['-fecha_venta', '-created_at'],
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(
                fields=['estado'],
                name='ventas_estado_784ecc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(
                fields=['estado_pago'],
                name='ventas_estado__5f294f_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(
                fields=['metodo_pago'],
                name='ventas_metodo__cff6da_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(
                fields=['cliente'],
                name='ventas_cliente_e319a3_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(
                fields=['usuario_registro'],
                name='ventas_usuario_c6d8ef_idx',
            ),
        ),
    ]
