# Generated by Django 6.0.4 on 2026-04-25 00:00

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialinventario'),
        ('ventas', '0002_expandir_modelo_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cantidad',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Cantidad vendida del producto.',
                        max_digits=10,
                        verbose_name='cantidad',
                    ),
                ),
                (
                    'precio_unitario',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Precio del producto al momento de la venta.',
                        max_digits=12,
                        verbose_name='precio unitario',
                    ),
                ),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Subtotal del detalle sin descuentos.',
                        max_digits=12,
                        verbose_name='subtotal',
                    ),
                ),
                (
                    'descuento',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Descuento aplicado al detalle.',
                        max_digits=12,
                        verbose_name='descuento',
                    ),
                ),
                (
                    'iva',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Valor del IVA aplicado al detalle.',
                        max_digits=12,
                        verbose_name='IVA',
                    ),
                ),
                (
                    'total',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Total final del detalle.',
                        max_digits=12,
                        verbose_name='total',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Fecha y hora de creacion del registro.',
                        verbose_name='fecha de creacion',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Fecha y hora de la ultima actualizacion.',
                        verbose_name='fecha de actualizacion',
                    ),
                ),
                (
                    'producto',
                    models.ForeignKey(
                        help_text='Producto vendido.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='detalles_venta',
                        to='inventario.producto',
                        verbose_name='producto',
                    ),
                ),
                (
                    'venta',
                    models.ForeignKey(
                        help_text='Venta a la que pertenece este detalle.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detalles',
                        to='ventas.venta',
                        verbose_name='venta',
                    ),
                ),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
                'db_table': 'detalles_venta',
                'ordering': ['venta', 'producto'],
            },
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(
                fields=['venta'],
                name='detalles_ve_venta_i_7d158c_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(
                fields=['producto'],
                name='detalles_ve_product_640123_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(
                fields=['created_at'],
                name='detalles_ve_created_b91078_idx',
            ),
        ),
    ]
