# Generated by Django 6.0.4 on 2026-04-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_email_alter_usuario_id'),
        ('ventas', '0003_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'monto_abonado',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Valor abonado a la venta.',
                        max_digits=12,
                        verbose_name='monto abonado',
                    ),
                ),
                (
                    'fecha_abono',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Fecha y hora en que se registro el abono.',
                        verbose_name='fecha de abono',
                    ),
                ),
                (
                    'metodo_pago',
                    models.CharField(
                        choices=[
                            ('EFECTIVO', 'Efectivo'),
                            ('TARJETA', 'Tarjeta'),
                            ('TRANSFERENCIA', 'Transferencia'),
                        ],
                        help_text=(
                            'Metodo de pago con el que se realizo el abono.'
                        ),
                        max_length=20,
                        verbose_name='metodo de pago',
                    ),
                ),
                (
                    'referencia_pago',
                    models.CharField(
                        blank=True,
                        help_text=(
                            'Numero de transaccion o referencia del pago.'
                        ),
                        max_length=100,
                        verbose_name='referencia de pago',
                    ),
                ),
                (
                    'observaciones',
                    models.TextField(
                        blank=True,
                        help_text='Observaciones adicionales del abono.',
                        verbose_name='observaciones',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Fecha y hora de creacion del registro.',
                        verbose_name='fecha de creacion',
                    ),
                ),
                (
                    'usuario_registro',
                    models.ForeignKey(
                        help_text='Usuario que registro el abono.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='abonos_registrados',
                        to='usuario.usuario',
                        verbose_name='usuario de registro',
                    ),
                ),
                (
                    'venta',
                    models.ForeignKey(
                        help_text='Venta sobre la cual se registra el abono.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='abonos',
                        to='ventas.venta',
                        verbose_name='venta',
                    ),
                ),
            ],
            options={
                'verbose_name': 'abono',
                'verbose_name_plural': 'abonos',
                'db_table': 'abonos',
                'ordering': ['-fecha_abono', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(
                fields=['venta'],
                name='abonos_venta_id_5b9338_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(
                fields=['fecha_abono'],
                name='abonos_fecha_a_ec854d_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(
                fields=['metodo_pago'],
                name='abonos_metodo__2db01f_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(
                fields=['usuario_registro'],
                name='abonos_usuario_b88d16_idx',
            ),
        ),
    ]
