# Generated by Django 6.0.4 on 2026-05-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactusNumberingRange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('factus_id', models.PositiveIntegerField(unique=True)),
                ('document_code', models.CharField(default='01', max_length=10)),
                ('prefix', models.CharField(max_length=20)),
                ('from_number', models.PositiveIntegerField(default=0)),
                ('to_number', models.PositiveIntegerField(default=0)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('resolution_number', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_credit_note_range', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'rango de numeracion Factus',
                'verbose_name_plural': 'rangos de numeracion Factus',
                'db_table': 'factus_numbering_ranges',
            },
        ),
        migrations.CreateModel(
            name='FacturacionElectronicaConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_enabled', models.BooleanField(default=False, verbose_name='facturacion habilitada')),
                (
                    'environment',
                    models.CharField(
                        choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Produccion')],
                        default='SANDBOX',
                        max_length=20,
                        verbose_name='ambiente',
                    ),
                ),
                ('auto_emitir_al_terminar', models.BooleanField(default=True, verbose_name='auto emitir al terminar')),
                ('auto_enviar_email', models.BooleanField(default=False, verbose_name='auto enviar email')),
                ('company_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot de empresa')),
                ('last_connection_status', models.CharField(blank=True, max_length=50, verbose_name='ultimo estado de conexion')),
                ('last_connection_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima verificacion de conexion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'active_bill_range',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='configs_factura',
                        to='ventas.factusnumberingrange',
                    ),
                ),
                (
                    'active_credit_note_range',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='configs_nota_credito',
                        to='ventas.factusnumberingrange',
                    ),
                ),
            ],
            options={
                'verbose_name': 'configuracion de facturacion electronica',
                'verbose_name_plural': 'configuracion de facturacion electronica',
                'db_table': 'facturacion_electronica_config',
            },
        ),
        migrations.CreateModel(
            name='VentaFacturaElectronica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDIENTE_ENVIO', 'Pendiente de envio'),
                            ('EMITIDA', 'Emitida'),
                            ('ERROR', 'Error'),
                            ('ANULADA', 'Anulada'),
                        ],
                        default='PENDIENTE_ENVIO',
                        max_length=30,
                    ),
                ),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('cufe', models.CharField(blank=True, max_length=255)),
                ('resolution_number', models.CharField(blank=True, max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('email_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('credit_note_number', models.CharField(blank=True, max_length=100)),
                ('credit_note_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'numbering_range',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='facturas_emitidas',
                        to='ventas.factusnumberingrange',
                    ),
                ),
                (
                    'venta',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='factura_documento',
                        to='ventas.venta',
                    ),
                ),
            ],
            options={
                'verbose_name': 'factura electronica de venta',
                'verbose_name_plural': 'facturas electronicas de ventas',
                'db_table': 'ventas_factura_electronica',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronicaIntento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('EMITIR', 'Emitir'),
                            ('CONSULTAR', 'Consultar'),
                            ('ENVIAR_EMAIL', 'Enviar email'),
                            ('DESCARGAR_PDF', 'Descargar PDF'),
                            ('DESCARGAR_XML', 'Descargar XML'),
                            ('NOTA_CREDITO', 'Nota credito'),
                            ('SINCRONIZAR_RANGOS', 'Sincronizar rangos'),
                            ('VALIDAR_CONEXION', 'Validar conexion'),
                        ],
                        max_length=30,
                    ),
                ),
                ('is_success', models.BooleanField(default=False)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'factura',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='intentos',
                        to='ventas.ventafacturaelectronica',
                    ),
                ),
            ],
            options={
                'verbose_name': 'intento de factura electronica',
                'verbose_name_plural': 'intentos de factura electronica',
                'db_table': 'factura_electronica_intentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='factusnumberingrange',
            index=models.Index(fields=['factus_id'], name='factus_numb_factus__9706c1_idx'),
        ),
        migrations.AddIndex(
            model_name='factusnumberingrange',
            index=models.Index(fields=['document_code'], name='factus_numb_documen_746bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='factusnumberingrange',
            index=models.Index(fields=['is_active'], name='factus_numb_is_acti_fdec14_idx'),
        ),
        migrations.AddIndex(
            model_name='ventafacturaelectronica',
            index=models.Index(fields=['status'], name='ventas_fact_status_8c4b53_idx'),
        ),
        migrations.AddIndex(
            model_name='ventafacturaelectronica',
            index=models.Index(fields=['bill_number'], name='ventas_fact_bill_n_c3e0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ventafacturaelectronica',
            index=models.Index(fields=['cufe'], name='ventas_fact_cufe_e8dd8a_idx'),
        ),
    ]
