# Generated by Django 6.0.4 on 2026-05-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_facturacion_electronica'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='abono',
            new_name='abonos_venta_i_37e4e6_idx',
            old_name='abonos_venta_id_5b9338_idx',
        ),
        migrations.RenameIndex(
            model_name='abono',
            new_name='abonos_fecha_a_53998b_idx',
            old_name='abonos_fecha_a_ec854d_idx',
        ),
        migrations.RenameIndex(
            model_name='abono',
            new_name='abonos_metodo__cc1a57_idx',
            old_name='abonos_metodo__2db01f_idx',
        ),
        migrations.RenameIndex(
            model_name='abono',
            new_name='abonos_usuario_00fa3b_idx',
            old_name='abonos_usuario_b88d16_idx',
        ),
        migrations.RenameIndex(
            model_name='detalleventa',
            new_name='detalles_ve_venta_i_9d7cc0_idx',
            old_name='detalles_ve_venta_i_7d158c_idx',
        ),
        migrations.RenameIndex(
            model_name='detalleventa',
            new_name='detalles_ve_product_ed1f1c_idx',
            old_name='detalles_ve_product_640123_idx',
        ),
        migrations.RenameIndex(
            model_name='detalleventa',
            new_name='detalles_ve_created_efea5b_idx',
            old_name='detalles_ve_created_b91078_idx',
        ),
        migrations.RenameIndex(
            model_name='factusnumberingrange',
            new_name='factus_numb_factus__b39819_idx',
            old_name='factus_numb_factus__9706c1_idx',
        ),
        migrations.RenameIndex(
            model_name='factusnumberingrange',
            new_name='factus_numb_documen_8cd5b2_idx',
            old_name='factus_numb_documen_746bfe_idx',
        ),
        migrations.RenameIndex(
            model_name='factusnumberingrange',
            new_name='factus_numb_is_acti_a2e324_idx',
            old_name='factus_numb_is_acti_fdec14_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_estado_505824_idx',
            old_name='ventas_estado_784ecc_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_estado__5ceec7_idx',
            old_name='ventas_estado__5f294f_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_metodo__6717c5_idx',
            old_name='ventas_metodo__cff6da_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_cliente_b73e43_idx',
            old_name='ventas_cliente_e319a3_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_usuario_4a9aef_idx',
            old_name='ventas_usuario_c6d8ef_idx',
        ),
        migrations.RenameIndex(
            model_name='ventafacturaelectronica',
            new_name='ventas_fact_status_23a7b3_idx',
            old_name='ventas_fact_status_8c4b53_idx',
        ),
        migrations.RenameIndex(
            model_name='ventafacturaelectronica',
            new_name='ventas_fact_bill_nu_ec602d_idx',
            old_name='ventas_fact_bill_n_c3e0d2_idx',
        ),
        migrations.RenameIndex(
            model_name='ventafacturaelectronica',
            new_name='ventas_fact_cufe_121fc4_idx',
            old_name='ventas_fact_cufe_e8dd8a_idx',
        ),
    ]
