# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_remove_cliente_cliente_tipo_numero_documento_unique_and_more'),
        ('empresa', '0001_initial'),
        ('ventas', '0006_rename_abonos_venta_id_5b9338_idx_abonos_venta_i_37e4e6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactusCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Produccion')], default='SANDBOX', max_length=20, verbose_name='ambiente')),
                ('base_url', models.URLField(default='https://api-sandbox.factus.com.co')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'credencial Factus',
                'verbose_name_plural': 'credenciales Factus',
                'db_table': 'factus_credentials',
            },
        ),
        migrations.AddField(
            model_name='facturacionelectronicaconfig',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturacion_config', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='facturaelectronicaintento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica_intentos', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='factusnumberingrange',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factus_numbering_ranges', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='ventafacturaelectronica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_electronicas', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='factusnumberingrange',
            name='factus_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, help_text='Numero unico de venta generado automaticamente.', max_length=30, verbose_name='numero de venta'),
        ),
        migrations.AlterField(
            model_name='ventafacturaelectronica',
            name='reference_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='facturacionelectronicaconfig',
            index=models.Index(fields=['empresa'], name='facturacion_empresa_e68b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronicaintento',
            index=models.Index(fields=['empresa'], name='factura_ele_empresa_bd2029_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronicaintento',
            index=models.Index(fields=['action'], name='factura_ele_action_1b6d75_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronicaintento',
            index=models.Index(fields=['is_success'], name='factura_ele_is_succ_7530a1_idx'),
        ),
        migrations.AddIndex(
            model_name='factusnumberingrange',
            index=models.Index(fields=['empresa'], name='factus_numb_empresa_739d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa'], name='ventas_empresa_3befb2_idx'),
        ),
        migrations.AddIndex(
            model_name='ventafacturaelectronica',
            index=models.Index(fields=['empresa'], name='ventas_fact_empresa_f24f6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='factusnumberingrange',
            constraint=models.UniqueConstraint(fields=('empresa', 'factus_id'), name='factus_range_empresa_factus_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_venta'), name='venta_empresa_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='ventafacturaelectronica',
            constraint=models.UniqueConstraint(fields=('empresa', 'reference_code'), name='factura_electronica_empresa_reference_unique'),
        ),
        migrations.AddField(
            model_name='factuscredential',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factus_credentials', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddIndex(
            model_name='factuscredential',
            index=models.Index(fields=['empresa', 'environment'], name='factus_cred_empresa_31d107_idx'),
        ),
        migrations.AddIndex(
            model_name='factuscredential',
            index=models.Index(fields=['activo'], name='factus_cred_activo_47ee24_idx'),
        ),
        migrations.AddConstraint(
            model_name='factuscredential',
            constraint=models.UniqueConstraint(fields=('empresa', 'environment'), name='factus_credential_empresa_environment_unique'),
        ),
    ]
