# Generated by Django 5.2 on 2026-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='NIT', help_text='Tipo de documento del proveedor', max_length=3, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(help_text='Número único de documento (NIT, CC, CE)', max_length=20, unique=True, verbose_name='número de documento')),
                ('razon_social', models.CharField(help_text='Nombre legal o razón social del proveedor', max_length=200, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial o marca (opcional)', max_length=200, verbose_name='nombre comercial')),
                ('nombre_contacto', models.CharField(help_text='Nombre de la persona de contacto', max_length=100, verbose_name='nombre de contacto')),
                ('email', models.EmailField(help_text='Correo electrónico para contacto', max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(help_text='Número de teléfono fijo', max_length=20, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, help_text='Número de celular (opcional)', max_length=20, verbose_name='celular')),
                ('direccion', models.TextField(help_text='Dirección completa del proveedor', verbose_name='dirección')),
                ('ciudad', models.CharField(help_text='Ciudad donde se encuentra el proveedor', max_length=100, verbose_name='ciudad')),
                ('departamento', models.CharField(help_text='Departamento o estado', max_length=100, verbose_name='departamento')),
                ('tipo_productos', models.TextField(help_text='Descripción de los tipos de productos que suministra', verbose_name='tipo de productos')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO_15', 'Crédito 15 días'), ('CREDITO_30', 'Crédito 30 días'), ('CREDITO_60', 'Crédito 60 días')], default='CONTADO', help_text='Condiciones de pago acordadas', max_length=15, verbose_name='forma de pago')),
                ('cuenta_bancaria', models.CharField(blank=True, help_text='Número de cuenta bancaria (opcional)', max_length=50, verbose_name='cuenta bancaria')),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco (opcional)', max_length=100, verbose_name='banco')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el proveedor', verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el proveedor está activo en el sistema', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['numero_documento'], name='proveedores_numero__252160_idx'), models.Index(fields=['razon_social'], name='proveedores_razon_s_2d0255_idx'), models.Index(fields=['ciudad'], name='proveedores_ciudad_68ba84_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx'), models.Index(fields=['created_at'], name='proveedores_created_64f4fa_idx')],
            },
        ),
    ]
