# Generated by Django 6.0.4 on 2026-04-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social', 'nombre_comercial'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_created_64f4fa_idx',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el proveedor esta activo.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco asociado a la cuenta registrada.', max_length=100, verbose_name='banco'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, help_text='Numero de celular del proveedor.', max_length=20, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(help_text='Ciudad del proveedor.', max_length=100, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creacion del registro.', verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, help_text='Numero de cuenta bancaria del proveedor.', max_length=50, verbose_name='cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(help_text='Departamento del proveedor.', max_length=100, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(help_text='Direccion principal del proveedor.', verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(help_text='Correo electronico principal del proveedor.', max_length=254, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO_15', 'Credito 15 dias'), ('CREDITO_30', 'Credito 30 dias'), ('CREDITO_60', 'Credito 60 dias')], default='CONTADO', help_text='Condicion de pago acordada con el proveedor.', max_length=15, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre comercial o marca del proveedor.', max_length=200, verbose_name='nombre comercial'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(help_text='Nombre de la persona de contacto.', max_length=100, verbose_name='nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(help_text='Numero unico de identificacion del proveedor.', max_length=20, unique=True, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales del proveedor.', verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(help_text='Nombre legal o razon social del proveedor.', max_length=200, verbose_name='razon social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(help_text='Telefono principal del proveedor.', max_length=20, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria')], default='NIT', help_text='Tipo de documento del proveedor.', max_length=3, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_productos',
            field=models.TextField(help_text='Descripcion de los productos que suministra.', verbose_name='tipo de productos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima actualizacion.', verbose_name='fecha de actualizacion'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['tipo_documento'], name='proveedores_tipo_do_2a56b1_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['forma_pago'], name='proveedores_forma_p_9ef592_idx'),
        ),
    ]
