# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('proveedor', '0002_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(help_text='Numero unico de identificacion del proveedor.', max_length=20, verbose_name='numero de documento'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa'], name='proveedores_empresa_843a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='proveedor_empresa_documento_unique'),
        ),
    ]
