# Generated by Django 6.0.4 on 2026-04-25 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo_documento',
                    models.CharField(
                        choices=[
                            ('CC', 'Cedula de Ciudadania'),
                            ('NIT', 'NIT'),
                            ('CE', 'Cedula de Extranjeria'),
                            ('PASAPORTE', 'Pasaporte'),
                        ],
                        default='CC',
                        help_text='Tipo de documento del cliente.',
                        max_length=10,
                        verbose_name='tipo de documento',
                    ),
                ),
                (
                    'numero_documento',
                    models.CharField(
                        help_text='Numero unico de identificacion del cliente.',
                        max_length=20,
                        unique=True,
                        verbose_name='numero de documento',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        blank=True,
                        help_text=(
                            'Nombre del cliente cuando es persona natural.'
                        ),
                        max_length=200,
                        verbose_name='nombre',
                    ),
                ),
                (
                    'razon_social',
                    models.CharField(
                        blank=True,
                        help_text=(
                            'Razon social del cliente cuando es persona '
                            'juridica.'
                        ),
                        max_length=200,
                        verbose_name='razon social',
                    ),
                ),
                (
                    'nombre_comercial',
                    models.CharField(
                        blank=True,
                        help_text='Nombre comercial del cliente.',
                        max_length=200,
                        verbose_name='nombre comercial',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        help_text='Correo electronico del cliente.',
                        max_length=254,
                        verbose_name='correo electronico',
                    ),
                ),
                (
                    'telefono',
                    models.CharField(
                        help_text='Telefono principal del cliente.',
                        max_length=20,
                        verbose_name='telefono',
                    ),
                ),
                (
                    'celular',
                    models.CharField(
                        blank=True,
                        help_text='Numero de celular del cliente.',
                        max_length=20,
                        verbose_name='celular',
                    ),
                ),
                (
                    'direccion',
                    models.TextField(
                        help_text='Direccion principal del cliente.',
                        verbose_name='direccion',
                    ),
                ),
                (
                    'ciudad',
                    models.CharField(
                        help_text='Ciudad del cliente.',
                        max_length=100,
                        verbose_name='ciudad',
                    ),
                ),
                (
                    'departamento',
                    models.CharField(
                        help_text='Departamento del cliente.',
                        max_length=100,
                        verbose_name='departamento',
                    ),
                ),
                (
                    'codigo_postal',
                    models.CharField(
                        blank=True,
                        help_text='Codigo postal del cliente.',
                        max_length=20,
                        verbose_name='codigo postal',
                    ),
                ),
                (
                    'tipo_cliente',
                    models.CharField(
                        choices=[
                            ('NATURAL', 'Natural'),
                            ('JURIDICO', 'Juridico'),
                        ],
                        default='NATURAL',
                        help_text=(
                            'Define si el cliente es natural o juridico.'
                        ),
                        max_length=10,
                        verbose_name='tipo de cliente',
                    ),
                ),
                (
                    'regimen_tributario',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('SIMPLIFICADO', 'Simplificado'),
                            ('COMUN', 'Comun'),
                        ],
                        help_text='Regimen tributario del cliente.',
                        max_length=20,
                        verbose_name='regimen tributario',
                    ),
                ),
                (
                    'responsable_iva',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Indica si el cliente es responsable de IVA.'
                        ),
                        verbose_name='responsable de IVA',
                    ),
                ),
                (
                    'credito_disponible',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Credito disponible para ventas a credito.',
                        max_digits=12,
                        verbose_name='credito disponible',
                    ),
                ),
                (
                    'limite_credito',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Limite maximo de credito permitido.',
                        max_digits=12,
                        verbose_name='limite de credito',
                    ),
                ),
                (
                    'dias_plazo',
                    models.IntegerField(
                        default=0,
                        help_text='Dias maximos para pago a credito.',
                        verbose_name='dias de plazo',
                    ),
                ),
                (
                    'observaciones',
                    models.TextField(
                        blank=True,
                        help_text='Observaciones adicionales del cliente.',
                        verbose_name='observaciones',
                    ),
                ),
                (
                    'activo',
                    models.BooleanField(
                        default=True,
                        help_text='Indica si el cliente esta activo.',
                        verbose_name='activo',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Fecha y hora de creacion del registro.',
                        verbose_name='fecha de creacion',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            'Fecha y hora de la ultima actualizacion.'
                        ),
                        verbose_name='fecha de actualizacion',
                    ),
                ),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ['nombre', 'razon_social'],
                'indexes': [
                    models.Index(
                        fields=['numero_documento'],
                        name='clientes_numero__5f929e_idx',
                    ),
                    models.Index(
                        fields=['nombre'],
                        name='clientes_nombre_4f6f90_idx',
                    ),
                    models.Index(
                        fields=['razon_social'],
                        name='clientes_razon_s_9cc251_idx',
                    ),
                    models.Index(
                        fields=['tipo_cliente'],
                        name='clientes_tipo_cl_5e7ebd_idx',
                    ),
                    models.Index(
                        fields=['activo'],
                        name='clientes_activo_843762_idx',
                    ),
                ],
            },
        ),
    ]
