# Generated by Django 6.0.4 on 2026-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_numero__b55e8a_idx',
            old_name='clientes_numero__5f929e_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_nombre_4aa028_idx',
            old_name='clientes_nombre_4f6f90_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_razon_s_6d1478_idx',
            old_name='clientes_razon_s_9cc251_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_tipo_cl_8125a0_idx',
            old_name='clientes_tipo_cl_5e7ebd_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_activo_1f6d14_idx',
            old_name='clientes_activo_843762_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(help_text='Numero unico de identificacion del cliente.', max_length=20, verbose_name='numero de documento'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo_documento'], name='clientes_tipo_do_d5bb94_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='cliente_tipo_numero_documento_unique'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('limite_credito__gte', 0)), name='cliente_limite_credito_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('credito_disponible__gte', 0)), name='cliente_credito_disponible_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('dias_plazo__gte', 0)), name='cliente_dias_plazo_gte_0'),
        ),
    ]
