# Generated by Django 6.0.4 on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_clientes_numero__5f929e_idx_clientes_numero__b55e8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(
                blank=True,
                help_text='Digito de verificacion para clientes con NIT.',
                max_length=5,
                verbose_name='digito de verificacion',
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio_codigo',
            field=models.CharField(
                blank=True,
                help_text='Codigo DIAN del municipio requerido para facturacion electronica.',
                max_length=10,
                verbose_name='codigo de municipio',
            ),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(
                fields=['municipio_codigo'],
                name='clientes_municip_31515e_idx',
            ),
        ),
    ]
