# Generated by Django 6.0.4 on 2026-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_facturacion_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_municip_31515e_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, help_text='Digito de verificacion para NIT cuando aplique.', max_length=5, verbose_name='digito de verificacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio_codigo',
            field=models.CharField(blank=True, help_text='Codigo DIAN/Factus del municipio del cliente.', max_length=10, verbose_name='codigo de municipio'),
        ),
    ]
