# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_clientes_municip_31515e_idx_and_more'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='cliente_tipo_numero_documento_unique',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa'], name='clientes_empresa_4d6377_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='cliente_tipo_numero_documento_unique'),
        ),
    ]
