# Generated by Django 6.0.4 on 2026-04-27 23:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_detallefacturacompra_precio_venta_sugerido'),
        ('proveedor', '0002_alter_proveedor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del ingrediente o materia prima.', max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion adicional del ingrediente.', verbose_name='descripcion')),
                ('unidad_medida', models.CharField(choices=[('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('UNIDADES', 'Unidades')], help_text='Unidad base usada para stock y costos.', max_length=20, verbose_name='unidad de medida')),
                ('precio_por_unidad', models.DecimalField(decimal_places=4, help_text='Costo por unidad base del ingrediente.', max_digits=14, verbose_name='precio por unidad')),
                ('stock_actual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad disponible del ingrediente.', max_digits=14, verbose_name='stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad minima recomendada para reposicion.', max_digits=14, verbose_name='stock minimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creacion del registro.', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima actualizacion.', verbose_name='fecha de actualizacion')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor principal del ingrediente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='proveedor.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'db_table': 'ingredientes',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioIngredientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad ingresada del ingrediente.', max_digits=14, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Costo unitario del ingrediente al ingresar.', max_digits=14, verbose_name='precio unitario')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registra el ingreso.', verbose_name='fecha de ingreso')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura de compra asociada al ingreso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ingredientes', to='inventario.facturacompra', verbose_name='factura de compra')),
                ('ingrediente', models.ForeignKey(help_text='Ingrediente asociado al ingreso de inventario.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='fabricante.ingrediente', verbose_name='ingrediente')),
                ('usuario', models.ForeignKey(help_text='Usuario que registra el ingreso del ingrediente.', on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_ingredientes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'ingreso de inventario de ingrediente',
                'verbose_name_plural': 'ingresos de inventario de ingredientes',
                'db_table': 'inventario_ingredientes',
                'ordering': ['-fecha_ingreso', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(fields=['nombre'], name='ingrediente_nombre_b291c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(fields=['unidad_medida'], name='ingrediente_unidad__5fb090_idx'),
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(fields=['proveedor'], name='ingrediente_proveed_f784dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(fields=['stock_actual'], name='ingrediente_stock_a_e94305_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioingredientes',
            index=models.Index(fields=['ingrediente'], name='inventario__ingredi_9981b9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioingredientes',
            index=models.Index(fields=['fecha_ingreso'], name='inventario__fecha_i_6dcce0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioingredientes',
            index=models.Index(fields=['factura'], name='inventario__factura_138c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioingredientes',
            index=models.Index(fields=['usuario'], name='inventario__usuario_9db85f_idx'),
        ),
    ]
