# Generated by Django 6.0.4 on 2026-04-27 23:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0001_initial'),
        ('inventario', '0006_detallefacturacompra_precio_venta_sugerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFabricado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto fabricado.', max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(help_text='Descripcion del producto fabricado.', verbose_name='descripcion')),
                ('unidad_medida', models.CharField(choices=[('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('UNIDADES', 'Unidades')], help_text='Unidad de medida del producto terminado.', max_length=20, verbose_name='unidad de medida')),
                ('cantidad_producida', models.DecimalField(decimal_places=4, help_text='Cantidad producida por lote.', max_digits=14, verbose_name='cantidad producida')),
                ('costo_produccion', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo total de produccion por lote.', max_digits=14, verbose_name='costo de produccion')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo unitario calculado del producto fabricado.', max_digits=14, verbose_name='costo unitario')),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio sugerido de venta al publico.', max_digits=14, verbose_name='precio de venta sugerido')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio final de venta del producto.', max_digits=14, verbose_name='precio de venta')),
                ('margen_utilidad', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Margen de utilidad calculado por unidad.', max_digits=14, verbose_name='margen de utilidad')),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de utilidad calculado.', max_digits=7, verbose_name='porcentaje de utilidad')),
                ('tiempo_produccion', models.IntegerField(help_text='Tiempo estimado de produccion por lote en minutos.', verbose_name='tiempo de produccion')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creacion del registro.', verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima actualizacion.', verbose_name='fecha de actualizacion')),
                ('producto_final', models.ForeignKey(blank=True, help_text='Producto de inventario asociado al producto fabricado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_fabricados', to='inventario.producto', verbose_name='producto final')),
            ],
            options={
                'verbose_name': 'producto fabricado',
                'verbose_name_plural': 'productos fabricados',
                'db_table': 'productos_fabricados',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientesProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=4, help_text='Cantidad necesaria del ingrediente para un lote.', max_digits=14, verbose_name='cantidad necesaria')),
                ('unidad_medida', models.CharField(choices=[('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('UNIDADES', 'Unidades')], help_text='Unidad de medida usada en la receta.', max_length=20, verbose_name='unidad de medida')),
                ('costo_ingrediente', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo calculado del ingrediente dentro del lote.', max_digits=14, verbose_name='costo del ingrediente')),
                ('ingrediente', models.ForeignKey(help_text='Ingrediente usado en la receta del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='productos_receta', to='fabricante.ingrediente', verbose_name='ingrediente')),
                ('producto_fabricado', models.ForeignKey(help_text='Producto fabricado al que pertenece la receta.', on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='fabricante.productofabricado', verbose_name='producto fabricado')),
            ],
            options={
                'verbose_name': 'ingrediente de producto',
                'verbose_name_plural': 'ingredientes de producto',
                'db_table': 'ingredientes_producto',
                'ordering': ['producto_fabricado', 'ingrediente'],
            },
        ),
        migrations.AddIndex(
            model_name='productofabricado',
            index=models.Index(fields=['nombre'], name='productos_f_nombre_e0628b_idx'),
        ),
        migrations.AddIndex(
            model_name='productofabricado',
            index=models.Index(fields=['unidad_medida'], name='productos_f_unidad__3b02be_idx'),
        ),
        migrations.AddIndex(
            model_name='productofabricado',
            index=models.Index(fields=['producto_final'], name='productos_f_product_d21b20_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientesproducto',
            index=models.Index(fields=['producto_fabricado'], name='ingrediente_product_ee5d14_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientesproducto',
            index=models.Index(fields=['ingrediente'], name='ingrediente_ingredi_598e90_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredientesproducto',
            constraint=models.UniqueConstraint(fields=('producto_fabricado', 'ingrediente'), name='unique_ingrediente_por_producto_fabricado'),
        ),
    ]
