# Generated by Django 6.0.4 on 2026-04-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0002_productofabricado_ingredientesproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('GALONES', 'Galones'), ('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('ONZAS_LIQUIDAS', 'Onzas liquidas'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('LIBRAS', 'Libras'), ('ONZAS', 'Onzas'), ('UNIDADES', 'Unidades')], help_text='Unidad base usada para stock y costos.', max_length=20, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='ingredientesproducto',
            name='unidad_medida',
            field=models.CharField(choices=[('GALONES', 'Galones'), ('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('ONZAS_LIQUIDAS', 'Onzas liquidas'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('LIBRAS', 'Libras'), ('ONZAS', 'Onzas'), ('UNIDADES', 'Unidades')], help_text='Unidad de medida usada en la receta.', max_length=20, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='productofabricado',
            name='unidad_medida',
            field=models.CharField(choices=[('GALONES', 'Galones'), ('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('ONZAS_LIQUIDAS', 'Onzas liquidas'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('LIBRAS', 'Libras'), ('ONZAS', 'Onzas'), ('UNIDADES', 'Unidades')], help_text='Unidad de medida del producto terminado.', max_length=20, verbose_name='unidad de medida'),
        ),
    ]
