# Generated by Django 6.0.4 on 2026-04-28 04:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0004_alter_ingrediente_unidad_medida_and_more'),
        ('inventario', '0006_detallefacturacompra_precio_venta_sugerido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productofabricado',
            name='stock_fabricado_disponible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad fabricada pendiente por empacar o despachar.', max_digits=14, verbose_name='stock fabricado disponible'),
        ),
        migrations.AddField(
            model_name='productofabricado',
            name='total_producido_acumulado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad historica producida de este producto.', max_digits=14, verbose_name='total producido acumulado'),
        ),
        migrations.CreateModel(
            name='PresentacionProductoFabricado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre comercial de la presentacion.', max_length=200, verbose_name='nombre')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=4, help_text='Contenido de cada unidad vendible.', max_digits=14, verbose_name='cantidad por unidad')),
                ('unidad_medida', models.CharField(choices=[('GARRAFAS', 'Garrafas'), ('GALONES', 'Galones'), ('LITROS', 'Litros'), ('MILILITROS', 'Mililitros'), ('ONZAS_LIQUIDAS', 'Onzas liquidas'), ('KILOGRAMOS', 'Kilogramos'), ('GRAMOS', 'Gramos'), ('LIBRAS', 'Libras'), ('ONZAS', 'Onzas'), ('UNIDADES', 'Unidades')], help_text='Unidad de la presentacion vendible.', max_length=20, verbose_name='unidad de medida')),
                ('costo_unitario_presentacion', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo calculado por unidad de la presentacion.', max_digits=14, verbose_name='costo unitario de presentacion')),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio sugerido de venta por presentacion.', max_digits=14, verbose_name='precio de venta sugerido')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio final de venta por presentacion.', max_digits=14, verbose_name='precio de venta')),
                ('margen_utilidad', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Margen actual por presentacion.', max_digits=14, verbose_name='margen de utilidad')),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rentabilidad actual por presentacion.', max_digits=7, verbose_name='porcentaje de utilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('producto_fabricado', models.ForeignKey(help_text='Producto fabricado del que nace la presentacion.', on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='fabricante.productofabricado', verbose_name='producto fabricado')),
                ('producto_inventario', models.ForeignKey(blank=True, help_text='Producto de inventario vinculado a esta presentacion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentaciones_fabricadas', to='inventario.producto', verbose_name='producto de inventario')),
            ],
            options={
                'verbose_name': 'presentacion de producto fabricado',
                'verbose_name_plural': 'presentaciones de productos fabricados',
                'db_table': 'presentaciones_producto_fabricado',
                'ordering': ['producto_fabricado', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEmpaquePresentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_unidades', models.DecimalField(decimal_places=4, help_text='Cantidad de unidades empaquetadas.', max_digits=14, verbose_name='cantidad de unidades')),
                ('cantidad_consumida_lote', models.DecimalField(decimal_places=4, help_text='Cantidad del lote consumida por el empaque.', max_digits=14, verbose_name='cantidad consumida del lote')),
                ('fecha_empaque', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de empaque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_empaque_presentaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_empaque', to='fabricante.presentacionproductofabricado', verbose_name='presentacion')),
            ],
            options={
                'verbose_name': 'movimiento de empaque',
                'verbose_name_plural': 'movimientos de empaque',
                'db_table': 'movimientos_empaque_presentacion',
                'ordering': ['-fecha_empaque', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='presentacionproductofabricado',
            index=models.Index(fields=['producto_fabricado'], name='presentacio_product_4ba4db_idx'),
        ),
        migrations.AddIndex(
            model_name='presentacionproductofabricado',
            index=models.Index(fields=['unidad_medida'], name='presentacio_unidad__3cde11_idx'),
        ),
        migrations.AddIndex(
            model_name='presentacionproductofabricado',
            index=models.Index(fields=['producto_inventario'], name='presentacio_product_217a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoempaquepresentacion',
            index=models.Index(fields=['presentacion'], name='movimientos_present_e2fbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoempaquepresentacion',
            index=models.Index(fields=['fecha_empaque'], name='movimientos_fecha_e_763297_idx'),
        ),
    ]
