# Generated by Django 6.0.4 on 2026-05-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0006_multitenant_empresa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingrediente',
            new_name='ingrediente_empresa_75f2c8_idx',
            old_name='ingrediente_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='ingredientesproducto',
            new_name='ingrediente_empresa_592dda_idx',
            old_name='ingredientep_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioingredientes',
            new_name='inventario__empresa_13dca6_idx',
            old_name='inventarioi_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoempaquepresentacion',
            new_name='movimientos_empresa_6bc6e3_idx',
            old_name='movimientoe_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='presentacionproductofabricado',
            new_name='presentacio_empresa_d7b70a_idx',
            old_name='presentacio_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='productofabricado',
            new_name='productos_f_empresa_76c7fb_idx',
            old_name='productofab_empresa_idx',
        ),
    ]
