# Generated by Django 6.0.4 on 2026-05-01 02:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cierre', models.DateField(help_text='Fecha correspondiente al cierre diario de caja.', unique=True, verbose_name='fecha de cierre')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registro el cierre.', verbose_name='fecha de registro')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de las ventas terminadas del dia.', max_digits=12, verbose_name='total de ventas')),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vendido en efectivo durante el dia.', max_digits=12, verbose_name='total en efectivo')),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vendido por pagos con tarjeta.', max_digits=12, verbose_name='total en tarjeta')),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vendido por transferencias bancarias.', max_digits=12, verbose_name='total en transferencia')),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vendido a credito durante el dia.', max_digits=12, verbose_name='total a credito')),
                ('total_abonos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de abonos en efectivo recibidos en el dia.', max_digits=12, verbose_name='total de abonos')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de los gastos operativos registrados.', max_digits=12, verbose_name='total de gastos')),
                ('gastos_operativos', models.JSONField(blank=True, default=dict, help_text='Desglose JSON de gastos operativos del dia por concepto.', verbose_name='gastos operativos')),
                ('ventas_por_categoria', models.JSONField(blank=True, default=dict, help_text='Resumen JSON de ventas del dia agrupadas por categoria.', verbose_name='ventas por categoria')),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efectivo esperado segun ventas en efectivo y abonos del dia.', max_digits=12, verbose_name='efectivo esperado')),
                ('efectivo_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efectivo contado fisicamente al cerrar la caja.', max_digits=12, verbose_name='efectivo real')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia entre el efectivo real y el efectivo esperado.', max_digits=12, verbose_name='diferencia')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el cierre.', verbose_name='observaciones')),
                ('usuario_cierre', models.ForeignKey(help_text='Usuario responsable de registrar el cierre.', on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL, verbose_name='usuario de cierre')),
            ],
            options={
                'verbose_name': 'cierre de caja',
                'verbose_name_plural': 'cierres de caja',
                'db_table': 'cierres_caja',
                'ordering': ['-fecha_cierre', '-fecha_registro'],
                'indexes': [models.Index(fields=['fecha_cierre'], name='cierres_caj_fecha_c_a950f3_idx'), models.Index(fields=['fecha_registro'], name='cierres_caj_fecha_r_21156b_idx'), models.Index(fields=['usuario_cierre'], name='cierres_caj_usuario_f75a9a_idx')],
            },
        ),
    ]
