# Generated by Django 6.0.4 on 2026-05-01 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_informe', models.CharField(choices=[('VENTAS_PERIODO', 'Ventas por periodo'), ('PRODUCTOS_MAS_VENDIDOS', 'Productos mas vendidos'), ('CLIENTES_TOP', 'Clientes top'), ('INVENTARIO_VALORIZADO', 'Inventario valorizado'), ('CUENTAS_POR_COBRAR', 'Cuentas por cobrar'), ('CIERRE_CAJA', 'Cierre de caja')], help_text='Categoria funcional del informe generado.', max_length=40, verbose_name='tipo de informe')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se genero el informe.', verbose_name='fecha de generacion')),
                ('fecha_inicio', models.DateField(help_text='Fecha inicial del periodo consultado.', verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha final del periodo consultado.', verbose_name='fecha de fin')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Datos estructurados utilizados para el informe.', verbose_name='datos')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF generado para el informe.', upload_to='informes/pdfs/', verbose_name='archivo PDF')),
                ('archivo_excel', models.FileField(blank=True, help_text='Archivo Excel generado para el informe.', upload_to='informes/excel/', verbose_name='archivo Excel')),
                ('usuario_genero', models.ForeignKey(help_text='Usuario responsable de generar el informe.', on_delete=django.db.models.deletion.PROTECT, related_name='informes_generados', to=settings.AUTH_USER_MODEL, verbose_name='usuario que genero')),
            ],
            options={
                'verbose_name': 'informe',
                'verbose_name_plural': 'informes',
                'db_table': 'informes_generados',
                'ordering': ['-fecha_generacion', '-id'],
                'indexes': [models.Index(fields=['tipo_informe'], name='informes_ge_tipo_in_917300_idx'), models.Index(fields=['fecha_generacion'], name='informes_ge_fecha_g_5af04b_idx'), models.Index(fields=['fecha_inicio'], name='informes_ge_fecha_i_e49a30_idx'), models.Index(fields=['fecha_fin'], name='informes_ge_fecha_f_d70649_idx'), models.Index(fields=['usuario_genero'], name='informes_ge_usuario_7edf88_idx')],
            },
        ),
    ]
