# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('informes', '0002_informe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='informe',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha_cierre',
            field=models.DateField(help_text='Fecha correspondiente al cierre diario de caja.', verbose_name='fecha de cierre'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['empresa'], name='cierres_caj_empresa_186d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='informe',
            index=models.Index(fields=['empresa'], name='informes_ge_empresa_045234_idx'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.UniqueConstraint(fields=('empresa', 'fecha_cierre'), name='cierre_caja_empresa_fecha_unique'),
        ),
    ]
