# Generated by Django 6.0.4 on 2026-05-18 21:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0006_empresaconfiguracion_ticket_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud')], default='local', max_length=20)),
                ('cloud_api_url', models.URLField(blank=True)),
                ('connectivity_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_connection_checked_at', models.DateTimeField(blank=True, null=True)),
                ('printer_config', models.JSONField(blank=True, default=dict)),
                ('offline_invoice_policy', models.CharField(choices=[('PREFACTURA', 'Prefactura interna'), ('TICKET', 'Ticket POS interno'), ('CONTINGENCIA', 'Contingencia DIAN')], default='PREFACTURA', max_length=20)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('invoice_retry_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_config', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_local_config',
            },
        ),
        migrations.CreateModel(
            name='LocalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('fingerprint_hash', models.CharField(blank=True, max_length=255)),
                ('is_server', models.BooleanField(default=False)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_devices', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_local_devices',
            },
        ),
        migrations.CreateModel(
            name='LocalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_key', models.CharField(max_length=120, unique=True)),
                ('plan', models.CharField(default='LOCAL_LIFETIME', max_length=60)),
                ('signature', models.TextField(blank=True)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('support_until', models.DateField(blank=True, null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE', 'Grace'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_license', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_local_licenses',
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='offline.localdevice')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_pos_terminals',
            },
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_sesiones', to='empresa.empresa')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to='offline.posterminal')),
            ],
            options={
                'db_table': 'offline_cajas_sesiones',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_uuid', models.UUIDField()),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_outbox', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_sync_outbox',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('CLOUD', 'Cloud'), ('FACTUS', 'Factus')], max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_logs', to='empresa.empresa')),
            ],
            options={
                'db_table': 'offline_connectivity_logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['empresa', 'target'], name='offline_con_empresa_8c35e2_idx'), models.Index(fields=['checked_at'], name='offline_con_checked_19396d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='localdevice',
            index=models.Index(fields=['empresa'], name='offline_loc_empresa_f8845a_idx'),
        ),
        migrations.AddIndex(
            model_name='localdevice',
            index=models.Index(fields=['is_server'], name='offline_loc_is_serv_97060a_idx'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['empresa'], name='offline_pos_empresa_148a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['code'], name='offline_pos_code_6ea8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['is_active'], name='offline_pos_is_acti_c07340_idx'),
        ),
        migrations.AddConstraint(
            model_name='posterminal',
            constraint=models.UniqueConstraint(fields=('empresa', 'code'), name='pos_terminal_empresa_code_unique'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['empresa'], name='offline_caj_empresa_3db464_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['terminal', 'estado'], name='offline_caj_termina_f5651d_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['opened_at'], name='offline_caj_opened__a1c6b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('terminal',), name='caja_sesion_terminal_abierta_unique'),
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['empresa', 'status'], name='offline_syn_empresa_a66d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['aggregate_type', 'aggregate_uuid'], name='offline_syn_aggrega_7d97a8_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['next_retry_at'], name='offline_syn_next_re_af86bf_idx'),
        ),
    ]
