# Generated by Django 6.0.4 on 2026-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localconfig',
            name='wizard_completed',
            field=models.BooleanField(default=False),
        ),
    ]
