"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _get_bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _get_csv_env(name: str, default=None) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return list(default or [])
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-txm643xxb+-75c0_vvpb4e87t804x(i!zrmse6q#=ai@70m=jp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env('DEBUG', True)
TESTING = 'test' in sys.argv

MALLOR_MODE = os.getenv('MALLOR_MODE', 'cloud').strip().lower()
MALLOR_LOCAL_SERVER = _get_bool_env('MALLOR_LOCAL_SERVER', MALLOR_MODE == 'local')
MALLOR_LAN_HOST = os.getenv('MALLOR_LAN_HOST', '').strip()
MALLOR_SERVE_FRONTEND = _get_bool_env(
    'MALLOR_SERVE_FRONTEND',
    MALLOR_LOCAL_SERVER,
)
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
HAS_WHITENOISE = find_spec('whitenoise') is not None

ALLOWED_HOSTS = _get_csv_env('ALLOWED_HOSTS') or [
    host
    for host in [
        'localhost',
        '127.0.0.1',
        '[::1]',
        MALLOR_LAN_HOST,
        RENDER_EXTERNAL_HOSTNAME,
    ]
    if host
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'empresa',
    'usuario',
    'offline',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'cliente',
    'fabricante',
    'IA',
    'informes',
    'inventario',
    'proveedor',
    'ventas',
]

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuario.Usuario'

# Configuración de campos auto-incrementales
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'empresa.middleware.EmpresaActivaMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'mallor'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if DATABASE_URL:
    try:
        import dj_database_url
    except ImportError as exc:
        raise ImportError(
            'DATABASE_URL requiere instalar dj-database-url.',
        ) from exc

    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '600')),
        ssl_require=_get_bool_env('DB_SSL_REQUIRE', not DEBUG),
    )
elif not DEBUG and MALLOR_MODE == 'cloud':
    raise ImproperlyConfigured(
        'DATABASE_URL es obligatorio en producción cloud. '
        'Configura la Internal Database URL de Render PostgreSQL.',
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
if HAS_WHITENOISE:
    STORAGES['staticfiles'] = {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    }
FRONTEND_DIST_DIR = BASE_DIR / 'frontend' / 'dist'
if FRONTEND_DIST_DIR.exists():
    STATICFILES_DIRS = [FRONTEND_DIST_DIR]
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', BASE_DIR / 'media'))

ENABLE_BASIC_AUTH = _get_bool_env(
    'MALLOR_ENABLE_BASIC_AUTH',
    DEBUG or TESTING,
)

_authentication_classes = [
    'usuario.authentication.MallorJWTAuthentication',
    'rest_framework.authentication.SessionAuthentication',
]
if ENABLE_BASIC_AUTH:
    _authentication_classes.append(
        'rest_framework.authentication.BasicAuthentication',
    )

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': _authentication_classes,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JWT_REMEMBER_REFRESH_LIFETIME = timedelta(days=14)
JWT_REFRESH_COOKIE_NAME = os.getenv(
    'JWT_REFRESH_COOKIE_NAME',
    'mallor_refresh',
)
JWT_REFRESH_COOKIE_SECURE = _get_bool_env(
    'JWT_REFRESH_COOKIE_SECURE',
    not DEBUG,
)
JWT_REFRESH_COOKIE_SAMESITE = os.getenv(
    'JWT_REFRESH_COOKIE_SAMESITE',
    'Lax',
)

FACTUS_CONFIG = {
    'BASE_URL': os.getenv('FACTUS_BASE_URL', 'https://api-sandbox.factus.com.co'),
    'CLIENT_ID': os.getenv('FACTUS_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('FACTUS_CLIENT_SECRET', ''),
    'USERNAME': os.getenv('FACTUS_USERNAME', ''),
    'PASSWORD': os.getenv('FACTUS_PASSWORD', ''),
    'TIMEOUT': int(os.getenv('FACTUS_TIMEOUT', '30')),
    'MAX_RETRIES': int(os.getenv('FACTUS_MAX_RETRIES', '2')),
    'VERIFY_SSL': _get_bool_env('FACTUS_VERIFY_SSL', True),
}
MALLOR_DATA_ENCRYPTION_KEY = os.getenv('MALLOR_DATA_ENCRYPTION_KEY', '')
MALLOR_CLOUD_BASE_URL = os.getenv('MALLOR_CLOUD_BASE_URL', 'https://mallor.onrender.com/').rstrip('/')

DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-chat')
DEEPSEEK_TIMEOUT = int(os.getenv('DEEPSEEK_TIMEOUT', '30'))
DEEPSEEK_TEMPERATURE = float(os.getenv('DEEPSEEK_TEMPERATURE', '0.1'))
IA_MAX_HISTORY_MESSAGES = int(os.getenv('IA_MAX_HISTORY_MESSAGES', '12'))
IA_MAX_TOOL_RESULTS = int(os.getenv('IA_MAX_TOOL_RESULTS', '20'))
IA_HISTORY_RESULT_MAX_CHARS = int(os.getenv('IA_HISTORY_RESULT_MAX_CHARS', '4000'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'mallor.factus': {
            'handlers': ['console'],
            'level': os.getenv('FACTUS_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'mallor.ia': {
            'handlers': ['console'],
            'level': os.getenv('IA_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'mallor.sync': {
            'handlers': ['console'],
            'level': os.getenv('SYNC_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# CORS settings
CORS_ALLOWED_ORIGINS = _get_csv_env('CORS_ALLOWED_ORIGINS', [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])
if MALLOR_LAN_HOST:
    CORS_ALLOWED_ORIGINS.extend([
        f"http://{MALLOR_LAN_HOST}:3000",
        f"http://{MALLOR_LAN_HOST}:5173",
    ])
if RENDER_EXTERNAL_HOSTNAME:
    CORS_ALLOWED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

CSRF_TRUSTED_ORIGINS = _get_csv_env('CSRF_TRUSTED_ORIGINS', [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])
if MALLOR_LAN_HOST:
    CSRF_TRUSTED_ORIGINS.extend([
        f"http://{MALLOR_LAN_HOST}",
        f"http://{MALLOR_LAN_HOST}:3000",
        f"http://{MALLOR_LAN_HOST}:5173",
    ])
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Solo en desarrollo

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-empresa-id',
    'x-terminal-id',
    'x-requested-with',
]

# Métodos permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _get_bool_env('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool_env(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    False,
)
SECURE_HSTS_PRELOAD = _get_bool_env('SECURE_HSTS_PRELOAD', False)
