# Generated by Django 6.0.4 on 2026-05-07 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_backfill_empresa_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('rol_empresa', models.CharField(max_length=20)),
                ('consulta', models.TextField()),
                ('respuesta', models.TextField()),
                ('herramienta_usada', models.CharField(blank=True, max_length=100)),
                ('parametros_herramienta', models.JSONField(blank=True, default=dict)),
                ('metadatos_resultado', models.JSONField(blank=True, default=dict)),
                ('feedback', models.CharField(blank=True, choices=[('UTIL', 'Util'), ('NO_UTIL', 'No util')], max_length=20)),
                ('feedback_comentario', models.TextField(blank=True)),
                ('tiempo_respuesta', models.FloatField(default=0.0)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_salida', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_ia', to='empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje IA',
                'verbose_name_plural': 'mensajes IA',
                'db_table': 'ia_mensajes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['empresa', 'usuario', 'sesion_id', 'created_at'], name='ia_msg_emp_usr_ses_fecha_idx'), models.Index(fields=['empresa', 'created_at'], name='ia_msg_empresa_fecha_idx'), models.Index(fields=['herramienta_usada'], name='ia_msg_herramienta_idx')],
            },
        ),
    ]
