# Generated by Django 6.0.4 on 2026-05-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='NIT del facturador electronico.', max_length=20, unique=True, verbose_name='NIT')),
                ('digito_verificacion', models.CharField(blank=True, max_length=5, verbose_name='digito de verificacion')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razon social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='nombre comercial')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('direccion', models.TextField(blank=True, verbose_name='direccion')),
                ('municipio_codigo', models.CharField(blank=True, max_length=10, verbose_name='codigo de municipio')),
                ('ambiente_facturacion', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Produccion')], default='SANDBOX', max_length=20, verbose_name='ambiente de facturacion')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresas',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['nit'], name='empresas_nit_f247f8_idx'), models.Index(fields=['activo'], name='empresas_activo_568d17_idx'), models.Index(fields=['ambiente_facturacion'], name='empresas_ambient_b8f0a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado')], default='EMPLEADO', max_length=20, verbose_name='rol')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario de empresa',
                'verbose_name_plural': 'usuarios de empresa',
                'db_table': 'empresas_usuarios',
                'indexes': [models.Index(fields=['empresa', 'usuario'], name='empresas_us_empresa_07b91a_idx'), models.Index(fields=['usuario', 'activo'], name='empresas_us_usuario_ba7273_idx'), models.Index(fields=['rol'], name='empresas_us_rol_7677fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario'), name='empresa_usuario_unique')],
            },
        ),
    ]
